---
- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Remove default config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add Nginx config
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"

- name: Start and enable Nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
